[package]
name = "rdkit-ffi"
version = "0.1.0"
edition = "2018"
include = [
    "rdkit/Code/GraphMol/*.cpp",
    "rdkit/Codee/GraphMol/SmilesParse",
    "rdkit/Code/RDGeneral",
    "src"
]

[dependencies]
cxx = "1.0"

[build-dependencies]
cxx-build = "1.0"